// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace quick_blue_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class PlatformBleInputProperty {
  kDisabled = 0,
  kNotification = 1,
  kIndication = 2
};

enum class PlatformBleOutputProperty {
  kWithResponse = 0,
  kWithoutResponse = 1
};

enum class PlatformConnectionState {
  kDisconnected = 0,
  kConnecting = 1,
  kConnected = 2,
  kDisconnecting = 3,
  kUnknown = 4
};

enum class PlatformGattStatus {
  kSuccess = 0,
  kFailure = 1
};


// Generated class from Pigeon that represents data sent in messages.
class PlatformScanResult {
 public:
  // Constructs an object setting all fields.
  explicit PlatformScanResult(
    const std::string& name,
    const std::string& device_id,
    const std::vector<uint8_t>& manufacturer_data_head,
    const std::vector<uint8_t>& manufacturer_data,
    int64_t rssi,
    const ::flutter::EncodableList& service_uuids,
    const ::flutter::EncodableMap& service_data);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& device_id() const;
  void set_device_id(std::string_view value_arg);

  const std::vector<uint8_t>& manufacturer_data_head() const;
  void set_manufacturer_data_head(const std::vector<uint8_t>& value_arg);

  const std::vector<uint8_t>& manufacturer_data() const;
  void set_manufacturer_data(const std::vector<uint8_t>& value_arg);

  int64_t rssi() const;
  void set_rssi(int64_t value_arg);

  const ::flutter::EncodableList& service_uuids() const;
  void set_service_uuids(const ::flutter::EncodableList& value_arg);

  const ::flutter::EncodableMap& service_data() const;
  void set_service_data(const ::flutter::EncodableMap& value_arg);

  bool operator==(const PlatformScanResult& other) const;
  bool operator!=(const PlatformScanResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PlatformScanResult& obj);
 private:
  static PlatformScanResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::string device_id_;
  std::vector<uint8_t> manufacturer_data_head_;
  std::vector<uint8_t> manufacturer_data_;
  int64_t rssi_;
  ::flutter::EncodableList service_uuids_;
  ::flutter::EncodableMap service_data_;
};


// Generated class from Pigeon that represents data sent in messages.
class PlatformConnectionStateChange {
 public:
  // Constructs an object setting all fields.
  explicit PlatformConnectionStateChange(
    const std::string& device_id,
    const PlatformConnectionState& state,
    const PlatformGattStatus& gatt_status);

  const std::string& device_id() const;
  void set_device_id(std::string_view value_arg);

  const PlatformConnectionState& state() const;
  void set_state(const PlatformConnectionState& value_arg);

  const PlatformGattStatus& gatt_status() const;
  void set_gatt_status(const PlatformGattStatus& value_arg);

  bool operator==(const PlatformConnectionStateChange& other) const;
  bool operator!=(const PlatformConnectionStateChange& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PlatformConnectionStateChange& obj);
 private:
  static PlatformConnectionStateChange FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string device_id_;
  PlatformConnectionState state_;
  PlatformGattStatus gatt_status_;
};


// Generated class from Pigeon that represents data sent in messages.
class PlatformServiceDiscovered {
 public:
  // Constructs an object setting all fields.
  explicit PlatformServiceDiscovered(
    const std::string& device_id,
    const std::string& service_uuid,
    const ::flutter::EncodableList& characteristics);

  const std::string& device_id() const;
  void set_device_id(std::string_view value_arg);

  const std::string& service_uuid() const;
  void set_service_uuid(std::string_view value_arg);

  const ::flutter::EncodableList& characteristics() const;
  void set_characteristics(const ::flutter::EncodableList& value_arg);

  bool operator==(const PlatformServiceDiscovered& other) const;
  bool operator!=(const PlatformServiceDiscovered& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PlatformServiceDiscovered& obj);
 private:
  static PlatformServiceDiscovered FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string device_id_;
  std::string service_uuid_;
  ::flutter::EncodableList characteristics_;
};


// Generated class from Pigeon that represents data sent in messages.
class PlatformCharacteristic {
 public:
  // Constructs an object setting all fields.
  explicit PlatformCharacteristic(
    const std::string& uuid,
    bool can_read,
    bool can_write_with_response,
    bool can_write_without_response,
    bool can_notify,
    bool can_indicate);

  const std::string& uuid() const;
  void set_uuid(std::string_view value_arg);

  bool can_read() const;
  void set_can_read(bool value_arg);

  bool can_write_with_response() const;
  void set_can_write_with_response(bool value_arg);

  bool can_write_without_response() const;
  void set_can_write_without_response(bool value_arg);

  bool can_notify() const;
  void set_can_notify(bool value_arg);

  bool can_indicate() const;
  void set_can_indicate(bool value_arg);

  bool operator==(const PlatformCharacteristic& other) const;
  bool operator!=(const PlatformCharacteristic& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PlatformCharacteristic& obj);
 private:
  static PlatformCharacteristic FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string uuid_;
  bool can_read_;
  bool can_write_with_response_;
  bool can_write_without_response_;
  bool can_notify_;
  bool can_indicate_;
};


// Generated class from Pigeon that represents data sent in messages.
class PlatformCharacteristicValueChanged {
 public:
  // Constructs an object setting all fields.
  explicit PlatformCharacteristicValueChanged(
    const std::string& device_id,
    const std::string& service_uuid,
    const std::string& characteristic_id,
    const std::vector<uint8_t>& value);

  const std::string& device_id() const;
  void set_device_id(std::string_view value_arg);

  const std::string& service_uuid() const;
  void set_service_uuid(std::string_view value_arg);

  const std::string& characteristic_id() const;
  void set_characteristic_id(std::string_view value_arg);

  const std::vector<uint8_t>& value() const;
  void set_value(const std::vector<uint8_t>& value_arg);

  bool operator==(const PlatformCharacteristicValueChanged& other) const;
  bool operator!=(const PlatformCharacteristicValueChanged& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PlatformCharacteristicValueChanged& obj);
 private:
  static PlatformCharacteristicValueChanged FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class QuickBlueApi;
  friend class QuickBlueFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string device_id_;
  std::string service_uuid_;
  std::string characteristic_id_;
  std::vector<uint8_t> value_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class QuickBlueApi {
 public:
  QuickBlueApi(const QuickBlueApi&) = delete;
  QuickBlueApi& operator=(const QuickBlueApi&) = delete;
  virtual ~QuickBlueApi() {}
  virtual ErrorOr<bool> IsBluetoothAvailable() = 0;
  virtual std::optional<FlutterError> StartScan(
    const ::flutter::EncodableList* service_uuids,
    const ::flutter::EncodableMap* manufacturer_data) = 0;
  virtual std::optional<FlutterError> StopScan() = 0;
  virtual std::optional<FlutterError> Connect(const std::string& device_id) = 0;
  virtual std::optional<FlutterError> Disconnect(const std::string& device_id) = 0;
  virtual void DiscoverServices(
    const std::string& device_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void SetNotifiable(
    const std::string& device_id,
    const std::string& service,
    const std::string& characteristic,
    const PlatformBleInputProperty& ble_input_property,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void ReadValue(
    const std::string& device_id,
    const std::string& service,
    const std::string& characteristic,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void WriteValue(
    const std::string& device_id,
    const std::string& service,
    const std::string& characteristic,
    const std::vector<uint8_t>& value,
    const PlatformBleOutputProperty& ble_output_property,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void RequestMtu(
    const std::string& device_id,
    int64_t expected_mtu,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;

  // The codec used by QuickBlueApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `QuickBlueApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    QuickBlueApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    QuickBlueApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  QuickBlueApi() = default;
};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class QuickBlueFlutterApi {
 public:
  QuickBlueFlutterApi(::flutter::BinaryMessenger* binary_messenger);
  QuickBlueFlutterApi(
    ::flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const ::flutter::StandardMessageCodec& GetCodec();
  void OnConnectionStateChange(
    const PlatformConnectionStateChange& state_change,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnServiceDiscovered(
    const PlatformServiceDiscovered& service_discovered,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnServiceDiscoveryComplete(
    const std::string& device_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnCharacteristicValueChanged(
    const PlatformCharacteristicValueChanged& value_changed,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
 private:
  ::flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace quick_blue_windows
#endif  // PIGEON_MESSAGES_G_H_
