// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace quick_blue_windows {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// PlatformWindowsSignalStrengthFilter

PlatformWindowsSignalStrengthFilter::PlatformWindowsSignalStrengthFilter() {}

PlatformWindowsSignalStrengthFilter::PlatformWindowsSignalStrengthFilter(
  const int64_t* in_range_threshold_in_d_bm,
  const int64_t* out_of_range_threshold_in_d_bm,
  const int64_t* out_of_range_timeout_millis,
  const int64_t* sampling_interval_millis)
 : in_range_threshold_in_d_bm_(in_range_threshold_in_d_bm ? std::optional<int64_t>(*in_range_threshold_in_d_bm) : std::nullopt),
    out_of_range_threshold_in_d_bm_(out_of_range_threshold_in_d_bm ? std::optional<int64_t>(*out_of_range_threshold_in_d_bm) : std::nullopt),
    out_of_range_timeout_millis_(out_of_range_timeout_millis ? std::optional<int64_t>(*out_of_range_timeout_millis) : std::nullopt),
    sampling_interval_millis_(sampling_interval_millis ? std::optional<int64_t>(*sampling_interval_millis) : std::nullopt) {}

const int64_t* PlatformWindowsSignalStrengthFilter::in_range_threshold_in_d_bm() const {
  return in_range_threshold_in_d_bm_ ? &(*in_range_threshold_in_d_bm_) : nullptr;
}

void PlatformWindowsSignalStrengthFilter::set_in_range_threshold_in_d_bm(const int64_t* value_arg) {
  in_range_threshold_in_d_bm_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PlatformWindowsSignalStrengthFilter::set_in_range_threshold_in_d_bm(int64_t value_arg) {
  in_range_threshold_in_d_bm_ = value_arg;
}


const int64_t* PlatformWindowsSignalStrengthFilter::out_of_range_threshold_in_d_bm() const {
  return out_of_range_threshold_in_d_bm_ ? &(*out_of_range_threshold_in_d_bm_) : nullptr;
}

void PlatformWindowsSignalStrengthFilter::set_out_of_range_threshold_in_d_bm(const int64_t* value_arg) {
  out_of_range_threshold_in_d_bm_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PlatformWindowsSignalStrengthFilter::set_out_of_range_threshold_in_d_bm(int64_t value_arg) {
  out_of_range_threshold_in_d_bm_ = value_arg;
}


const int64_t* PlatformWindowsSignalStrengthFilter::out_of_range_timeout_millis() const {
  return out_of_range_timeout_millis_ ? &(*out_of_range_timeout_millis_) : nullptr;
}

void PlatformWindowsSignalStrengthFilter::set_out_of_range_timeout_millis(const int64_t* value_arg) {
  out_of_range_timeout_millis_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PlatformWindowsSignalStrengthFilter::set_out_of_range_timeout_millis(int64_t value_arg) {
  out_of_range_timeout_millis_ = value_arg;
}


const int64_t* PlatformWindowsSignalStrengthFilter::sampling_interval_millis() const {
  return sampling_interval_millis_ ? &(*sampling_interval_millis_) : nullptr;
}

void PlatformWindowsSignalStrengthFilter::set_sampling_interval_millis(const int64_t* value_arg) {
  sampling_interval_millis_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PlatformWindowsSignalStrengthFilter::set_sampling_interval_millis(int64_t value_arg) {
  sampling_interval_millis_ = value_arg;
}


EncodableList PlatformWindowsSignalStrengthFilter::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(in_range_threshold_in_d_bm_ ? EncodableValue(*in_range_threshold_in_d_bm_) : EncodableValue());
  list.push_back(out_of_range_threshold_in_d_bm_ ? EncodableValue(*out_of_range_threshold_in_d_bm_) : EncodableValue());
  list.push_back(out_of_range_timeout_millis_ ? EncodableValue(*out_of_range_timeout_millis_) : EncodableValue());
  list.push_back(sampling_interval_millis_ ? EncodableValue(*sampling_interval_millis_) : EncodableValue());
  return list;
}

PlatformWindowsSignalStrengthFilter PlatformWindowsSignalStrengthFilter::FromEncodableList(const EncodableList& list) {
  PlatformWindowsSignalStrengthFilter decoded;
  auto& encodable_in_range_threshold_in_d_bm = list[0];
  if (!encodable_in_range_threshold_in_d_bm.IsNull()) {
    decoded.set_in_range_threshold_in_d_bm(std::get<int64_t>(encodable_in_range_threshold_in_d_bm));
  }
  auto& encodable_out_of_range_threshold_in_d_bm = list[1];
  if (!encodable_out_of_range_threshold_in_d_bm.IsNull()) {
    decoded.set_out_of_range_threshold_in_d_bm(std::get<int64_t>(encodable_out_of_range_threshold_in_d_bm));
  }
  auto& encodable_out_of_range_timeout_millis = list[2];
  if (!encodable_out_of_range_timeout_millis.IsNull()) {
    decoded.set_out_of_range_timeout_millis(std::get<int64_t>(encodable_out_of_range_timeout_millis));
  }
  auto& encodable_sampling_interval_millis = list[3];
  if (!encodable_sampling_interval_millis.IsNull()) {
    decoded.set_sampling_interval_millis(std::get<int64_t>(encodable_sampling_interval_millis));
  }
  return decoded;
}

bool PlatformWindowsSignalStrengthFilter::operator==(const PlatformWindowsSignalStrengthFilter& other) const {
  return PigeonInternalDeepEquals(in_range_threshold_in_d_bm_, other.in_range_threshold_in_d_bm_) && PigeonInternalDeepEquals(out_of_range_threshold_in_d_bm_, other.out_of_range_threshold_in_d_bm_) && PigeonInternalDeepEquals(out_of_range_timeout_millis_, other.out_of_range_timeout_millis_) && PigeonInternalDeepEquals(sampling_interval_millis_, other.sampling_interval_millis_);
}

bool PlatformWindowsSignalStrengthFilter::operator!=(const PlatformWindowsSignalStrengthFilter& other) const {
  return !(*this == other);
}

size_t PlatformWindowsSignalStrengthFilter::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(in_range_threshold_in_d_bm_);
  result = result * 31 + PigeonInternalDeepHash(out_of_range_threshold_in_d_bm_);
  result = result * 31 + PigeonInternalDeepHash(out_of_range_timeout_millis_);
  result = result * 31 + PigeonInternalDeepHash(sampling_interval_millis_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformWindowsSignalStrengthFilter& obj) {
  os << "PlatformWindowsSignalStrengthFilter(";
  os << "in_range_threshold_in_d_bm: ";
  if (obj.in_range_threshold_in_d_bm_) {
    os << PigeonInternalToString(*obj.in_range_threshold_in_d_bm_);
  }
  else {
    os << "null";
  }
  os << ", out_of_range_threshold_in_d_bm: ";
  if (obj.out_of_range_threshold_in_d_bm_) {
    os << PigeonInternalToString(*obj.out_of_range_threshold_in_d_bm_);
  }
  else {
    os << "null";
  }
  os << ", out_of_range_timeout_millis: ";
  if (obj.out_of_range_timeout_millis_) {
    os << PigeonInternalToString(*obj.out_of_range_timeout_millis_);
  }
  else {
    os << "null";
  }
  os << ", sampling_interval_millis: ";
  if (obj.sampling_interval_millis_) {
    os << PigeonInternalToString(*obj.sampling_interval_millis_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformWindowsSignalStrengthFilter& v) {
  return v.Hash();
}

// PlatformWindowsScanOptions

PlatformWindowsScanOptions::PlatformWindowsScanOptions() {}

PlatformWindowsScanOptions::PlatformWindowsScanOptions(
  const PlatformWindowsScanMode* scanning_mode,
  const PlatformWindowsSignalStrengthFilter* signal_strength_filter)
 : scanning_mode_(scanning_mode ? std::optional<PlatformWindowsScanMode>(*scanning_mode) : std::nullopt),
    signal_strength_filter_(signal_strength_filter ? std::make_unique<PlatformWindowsSignalStrengthFilter>(*signal_strength_filter) : nullptr) {}

PlatformWindowsScanOptions::PlatformWindowsScanOptions(const PlatformWindowsScanOptions& other)
 : scanning_mode_(other.scanning_mode_ ? std::optional<PlatformWindowsScanMode>(*other.scanning_mode_) : std::nullopt),
    signal_strength_filter_(other.signal_strength_filter_ ? std::make_unique<PlatformWindowsSignalStrengthFilter>(*other.signal_strength_filter_) : nullptr) {}

PlatformWindowsScanOptions& PlatformWindowsScanOptions::operator=(const PlatformWindowsScanOptions& other) {
  scanning_mode_ = other.scanning_mode_;
  signal_strength_filter_ = other.signal_strength_filter_ ? std::make_unique<PlatformWindowsSignalStrengthFilter>(*other.signal_strength_filter_) : nullptr;
  return *this;
}

const PlatformWindowsScanMode* PlatformWindowsScanOptions::scanning_mode() const {
  return scanning_mode_ ? &(*scanning_mode_) : nullptr;
}

void PlatformWindowsScanOptions::set_scanning_mode(const PlatformWindowsScanMode* value_arg) {
  scanning_mode_ = value_arg ? std::optional<PlatformWindowsScanMode>(*value_arg) : std::nullopt;
}

void PlatformWindowsScanOptions::set_scanning_mode(const PlatformWindowsScanMode& value_arg) {
  scanning_mode_ = value_arg;
}


const PlatformWindowsSignalStrengthFilter* PlatformWindowsScanOptions::signal_strength_filter() const {
  return signal_strength_filter_.get();
}

void PlatformWindowsScanOptions::set_signal_strength_filter(const PlatformWindowsSignalStrengthFilter* value_arg) {
  signal_strength_filter_ = value_arg ? std::make_unique<PlatformWindowsSignalStrengthFilter>(*value_arg) : nullptr;
}

void PlatformWindowsScanOptions::set_signal_strength_filter(const PlatformWindowsSignalStrengthFilter& value_arg) {
  signal_strength_filter_ = std::make_unique<PlatformWindowsSignalStrengthFilter>(value_arg);
}


EncodableList PlatformWindowsScanOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(scanning_mode_ ? CustomEncodableValue(*scanning_mode_) : EncodableValue());
  list.push_back(signal_strength_filter_ ? CustomEncodableValue(*signal_strength_filter_) : EncodableValue());
  return list;
}

PlatformWindowsScanOptions PlatformWindowsScanOptions::FromEncodableList(const EncodableList& list) {
  PlatformWindowsScanOptions decoded;
  auto& encodable_scanning_mode = list[0];
  if (!encodable_scanning_mode.IsNull()) {
    decoded.set_scanning_mode(std::any_cast<const PlatformWindowsScanMode&>(std::get<CustomEncodableValue>(encodable_scanning_mode)));
  }
  auto& encodable_signal_strength_filter = list[1];
  if (!encodable_signal_strength_filter.IsNull()) {
    decoded.set_signal_strength_filter(std::any_cast<const PlatformWindowsSignalStrengthFilter&>(std::get<CustomEncodableValue>(encodable_signal_strength_filter)));
  }
  return decoded;
}

bool PlatformWindowsScanOptions::operator==(const PlatformWindowsScanOptions& other) const {
  return PigeonInternalDeepEquals(scanning_mode_, other.scanning_mode_) && PigeonInternalDeepEquals(signal_strength_filter_, other.signal_strength_filter_);
}

bool PlatformWindowsScanOptions::operator!=(const PlatformWindowsScanOptions& other) const {
  return !(*this == other);
}

size_t PlatformWindowsScanOptions::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(scanning_mode_);
  result = result * 31 + PigeonInternalDeepHash(signal_strength_filter_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformWindowsScanOptions& obj) {
  os << "PlatformWindowsScanOptions(";
  os << "scanning_mode: ";
  if (obj.scanning_mode_) {
    os << PigeonInternalToString(*obj.scanning_mode_);
  }
  else {
    os << "null";
  }
  os << ", signal_strength_filter: ";
  if (obj.signal_strength_filter_) {
    os << *obj.signal_strength_filter_;
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformWindowsScanOptions& v) {
  return v.Hash();
}

// PlatformScanResult

PlatformScanResult::PlatformScanResult(
  const std::string& name,
  const std::string& device_id,
  const std::vector<uint8_t>& manufacturer_data_head,
  const std::vector<uint8_t>& manufacturer_data,
  int64_t rssi,
  const EncodableList& service_uuids,
  const EncodableMap& service_data)
 : name_(name),
    device_id_(device_id),
    manufacturer_data_head_(manufacturer_data_head),
    manufacturer_data_(manufacturer_data),
    rssi_(rssi),
    service_uuids_(service_uuids),
    service_data_(service_data) {}

const std::string& PlatformScanResult::name() const {
  return name_;
}

void PlatformScanResult::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& PlatformScanResult::device_id() const {
  return device_id_;
}

void PlatformScanResult::set_device_id(std::string_view value_arg) {
  device_id_ = value_arg;
}


const std::vector<uint8_t>& PlatformScanResult::manufacturer_data_head() const {
  return manufacturer_data_head_;
}

void PlatformScanResult::set_manufacturer_data_head(const std::vector<uint8_t>& value_arg) {
  manufacturer_data_head_ = value_arg;
}


const std::vector<uint8_t>& PlatformScanResult::manufacturer_data() const {
  return manufacturer_data_;
}

void PlatformScanResult::set_manufacturer_data(const std::vector<uint8_t>& value_arg) {
  manufacturer_data_ = value_arg;
}


int64_t PlatformScanResult::rssi() const {
  return rssi_;
}

void PlatformScanResult::set_rssi(int64_t value_arg) {
  rssi_ = value_arg;
}


const EncodableList& PlatformScanResult::service_uuids() const {
  return service_uuids_;
}

void PlatformScanResult::set_service_uuids(const EncodableList& value_arg) {
  service_uuids_ = value_arg;
}


const EncodableMap& PlatformScanResult::service_data() const {
  return service_data_;
}

void PlatformScanResult::set_service_data(const EncodableMap& value_arg) {
  service_data_ = value_arg;
}


EncodableList PlatformScanResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(device_id_));
  list.push_back(EncodableValue(manufacturer_data_head_));
  list.push_back(EncodableValue(manufacturer_data_));
  list.push_back(EncodableValue(rssi_));
  list.push_back(EncodableValue(service_uuids_));
  list.push_back(EncodableValue(service_data_));
  return list;
}

PlatformScanResult PlatformScanResult::FromEncodableList(const EncodableList& list) {
  PlatformScanResult decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::vector<uint8_t>>(list[2]),
    std::get<std::vector<uint8_t>>(list[3]),
    std::get<int64_t>(list[4]),
    std::get<EncodableList>(list[5]),
    std::get<EncodableMap>(list[6]));
  return decoded;
}

bool PlatformScanResult::operator==(const PlatformScanResult& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(device_id_, other.device_id_) && PigeonInternalDeepEquals(manufacturer_data_head_, other.manufacturer_data_head_) && PigeonInternalDeepEquals(manufacturer_data_, other.manufacturer_data_) && PigeonInternalDeepEquals(rssi_, other.rssi_) && PigeonInternalDeepEquals(service_uuids_, other.service_uuids_) && PigeonInternalDeepEquals(service_data_, other.service_data_);
}

bool PlatformScanResult::operator!=(const PlatformScanResult& other) const {
  return !(*this == other);
}

size_t PlatformScanResult::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(device_id_);
  result = result * 31 + PigeonInternalDeepHash(manufacturer_data_head_);
  result = result * 31 + PigeonInternalDeepHash(manufacturer_data_);
  result = result * 31 + PigeonInternalDeepHash(rssi_);
  result = result * 31 + PigeonInternalDeepHash(service_uuids_);
  result = result * 31 + PigeonInternalDeepHash(service_data_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformScanResult& obj) {
  os << "PlatformScanResult(";
  os << "name: ";
  os << PigeonInternalToString(obj.name_);
  os << ", device_id: ";
  os << PigeonInternalToString(obj.device_id_);
  os << ", manufacturer_data_head: ";
  os << PigeonInternalToString(obj.manufacturer_data_head_);
  os << ", manufacturer_data: ";
  os << PigeonInternalToString(obj.manufacturer_data_);
  os << ", rssi: ";
  os << PigeonInternalToString(obj.rssi_);
  os << ", service_uuids: ";
  os << PigeonInternalToString(obj.service_uuids_);
  os << ", service_data: ";
  os << PigeonInternalToString(obj.service_data_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformScanResult& v) {
  return v.Hash();
}

// PlatformConnectionStateChange

PlatformConnectionStateChange::PlatformConnectionStateChange(
  const std::string& device_id,
  const PlatformConnectionState& state,
  const PlatformGattStatus& gatt_status)
 : device_id_(device_id),
    state_(state),
    gatt_status_(gatt_status) {}

const std::string& PlatformConnectionStateChange::device_id() const {
  return device_id_;
}

void PlatformConnectionStateChange::set_device_id(std::string_view value_arg) {
  device_id_ = value_arg;
}


const PlatformConnectionState& PlatformConnectionStateChange::state() const {
  return state_;
}

void PlatformConnectionStateChange::set_state(const PlatformConnectionState& value_arg) {
  state_ = value_arg;
}


const PlatformGattStatus& PlatformConnectionStateChange::gatt_status() const {
  return gatt_status_;
}

void PlatformConnectionStateChange::set_gatt_status(const PlatformGattStatus& value_arg) {
  gatt_status_ = value_arg;
}


EncodableList PlatformConnectionStateChange::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(device_id_));
  list.push_back(CustomEncodableValue(state_));
  list.push_back(CustomEncodableValue(gatt_status_));
  return list;
}

PlatformConnectionStateChange PlatformConnectionStateChange::FromEncodableList(const EncodableList& list) {
  PlatformConnectionStateChange decoded(
    std::get<std::string>(list[0]),
    std::any_cast<const PlatformConnectionState&>(std::get<CustomEncodableValue>(list[1])),
    std::any_cast<const PlatformGattStatus&>(std::get<CustomEncodableValue>(list[2])));
  return decoded;
}

bool PlatformConnectionStateChange::operator==(const PlatformConnectionStateChange& other) const {
  return PigeonInternalDeepEquals(device_id_, other.device_id_) && PigeonInternalDeepEquals(state_, other.state_) && PigeonInternalDeepEquals(gatt_status_, other.gatt_status_);
}

bool PlatformConnectionStateChange::operator!=(const PlatformConnectionStateChange& other) const {
  return !(*this == other);
}

size_t PlatformConnectionStateChange::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(device_id_);
  result = result * 31 + PigeonInternalDeepHash(state_);
  result = result * 31 + PigeonInternalDeepHash(gatt_status_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformConnectionStateChange& obj) {
  os << "PlatformConnectionStateChange(";
  os << "device_id: ";
  os << PigeonInternalToString(obj.device_id_);
  os << ", state: ";
  os << PigeonInternalToString(obj.state_);
  os << ", gatt_status: ";
  os << PigeonInternalToString(obj.gatt_status_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformConnectionStateChange& v) {
  return v.Hash();
}

// PlatformServiceDiscovered

PlatformServiceDiscovered::PlatformServiceDiscovered(
  const std::string& device_id,
  const std::string& service_uuid,
  const EncodableList& characteristics)
 : device_id_(device_id),
    service_uuid_(service_uuid),
    characteristics_(characteristics) {}

const std::string& PlatformServiceDiscovered::device_id() const {
  return device_id_;
}

void PlatformServiceDiscovered::set_device_id(std::string_view value_arg) {
  device_id_ = value_arg;
}


const std::string& PlatformServiceDiscovered::service_uuid() const {
  return service_uuid_;
}

void PlatformServiceDiscovered::set_service_uuid(std::string_view value_arg) {
  service_uuid_ = value_arg;
}


const EncodableList& PlatformServiceDiscovered::characteristics() const {
  return characteristics_;
}

void PlatformServiceDiscovered::set_characteristics(const EncodableList& value_arg) {
  characteristics_ = value_arg;
}


EncodableList PlatformServiceDiscovered::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(device_id_));
  list.push_back(EncodableValue(service_uuid_));
  list.push_back(EncodableValue(characteristics_));
  return list;
}

PlatformServiceDiscovered PlatformServiceDiscovered::FromEncodableList(const EncodableList& list) {
  PlatformServiceDiscovered decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<EncodableList>(list[2]));
  return decoded;
}

bool PlatformServiceDiscovered::operator==(const PlatformServiceDiscovered& other) const {
  return PigeonInternalDeepEquals(device_id_, other.device_id_) && PigeonInternalDeepEquals(service_uuid_, other.service_uuid_) && PigeonInternalDeepEquals(characteristics_, other.characteristics_);
}

bool PlatformServiceDiscovered::operator!=(const PlatformServiceDiscovered& other) const {
  return !(*this == other);
}

size_t PlatformServiceDiscovered::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(device_id_);
  result = result * 31 + PigeonInternalDeepHash(service_uuid_);
  result = result * 31 + PigeonInternalDeepHash(characteristics_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformServiceDiscovered& obj) {
  os << "PlatformServiceDiscovered(";
  os << "device_id: ";
  os << PigeonInternalToString(obj.device_id_);
  os << ", service_uuid: ";
  os << PigeonInternalToString(obj.service_uuid_);
  os << ", characteristics: ";
  os << PigeonInternalToString(obj.characteristics_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformServiceDiscovered& v) {
  return v.Hash();
}

// PlatformCharacteristic

PlatformCharacteristic::PlatformCharacteristic(
  const std::string& uuid,
  bool can_read,
  bool can_write_with_response,
  bool can_write_without_response,
  bool can_notify,
  bool can_indicate)
 : uuid_(uuid),
    can_read_(can_read),
    can_write_with_response_(can_write_with_response),
    can_write_without_response_(can_write_without_response),
    can_notify_(can_notify),
    can_indicate_(can_indicate) {}

const std::string& PlatformCharacteristic::uuid() const {
  return uuid_;
}

void PlatformCharacteristic::set_uuid(std::string_view value_arg) {
  uuid_ = value_arg;
}


bool PlatformCharacteristic::can_read() const {
  return can_read_;
}

void PlatformCharacteristic::set_can_read(bool value_arg) {
  can_read_ = value_arg;
}


bool PlatformCharacteristic::can_write_with_response() const {
  return can_write_with_response_;
}

void PlatformCharacteristic::set_can_write_with_response(bool value_arg) {
  can_write_with_response_ = value_arg;
}


bool PlatformCharacteristic::can_write_without_response() const {
  return can_write_without_response_;
}

void PlatformCharacteristic::set_can_write_without_response(bool value_arg) {
  can_write_without_response_ = value_arg;
}


bool PlatformCharacteristic::can_notify() const {
  return can_notify_;
}

void PlatformCharacteristic::set_can_notify(bool value_arg) {
  can_notify_ = value_arg;
}


bool PlatformCharacteristic::can_indicate() const {
  return can_indicate_;
}

void PlatformCharacteristic::set_can_indicate(bool value_arg) {
  can_indicate_ = value_arg;
}


EncodableList PlatformCharacteristic::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(uuid_));
  list.push_back(EncodableValue(can_read_));
  list.push_back(EncodableValue(can_write_with_response_));
  list.push_back(EncodableValue(can_write_without_response_));
  list.push_back(EncodableValue(can_notify_));
  list.push_back(EncodableValue(can_indicate_));
  return list;
}

PlatformCharacteristic PlatformCharacteristic::FromEncodableList(const EncodableList& list) {
  PlatformCharacteristic decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[1]),
    std::get<bool>(list[2]),
    std::get<bool>(list[3]),
    std::get<bool>(list[4]),
    std::get<bool>(list[5]));
  return decoded;
}

bool PlatformCharacteristic::operator==(const PlatformCharacteristic& other) const {
  return PigeonInternalDeepEquals(uuid_, other.uuid_) && PigeonInternalDeepEquals(can_read_, other.can_read_) && PigeonInternalDeepEquals(can_write_with_response_, other.can_write_with_response_) && PigeonInternalDeepEquals(can_write_without_response_, other.can_write_without_response_) && PigeonInternalDeepEquals(can_notify_, other.can_notify_) && PigeonInternalDeepEquals(can_indicate_, other.can_indicate_);
}

bool PlatformCharacteristic::operator!=(const PlatformCharacteristic& other) const {
  return !(*this == other);
}

size_t PlatformCharacteristic::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(uuid_);
  result = result * 31 + PigeonInternalDeepHash(can_read_);
  result = result * 31 + PigeonInternalDeepHash(can_write_with_response_);
  result = result * 31 + PigeonInternalDeepHash(can_write_without_response_);
  result = result * 31 + PigeonInternalDeepHash(can_notify_);
  result = result * 31 + PigeonInternalDeepHash(can_indicate_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformCharacteristic& obj) {
  os << "PlatformCharacteristic(";
  os << "uuid: ";
  os << PigeonInternalToString(obj.uuid_);
  os << ", can_read: ";
  os << PigeonInternalToString(obj.can_read_);
  os << ", can_write_with_response: ";
  os << PigeonInternalToString(obj.can_write_with_response_);
  os << ", can_write_without_response: ";
  os << PigeonInternalToString(obj.can_write_without_response_);
  os << ", can_notify: ";
  os << PigeonInternalToString(obj.can_notify_);
  os << ", can_indicate: ";
  os << PigeonInternalToString(obj.can_indicate_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformCharacteristic& v) {
  return v.Hash();
}

// PlatformCharacteristicValueChanged

PlatformCharacteristicValueChanged::PlatformCharacteristicValueChanged(
  const std::string& device_id,
  const std::string& service_uuid,
  const std::string& characteristic_id,
  const std::vector<uint8_t>& value)
 : device_id_(device_id),
    service_uuid_(service_uuid),
    characteristic_id_(characteristic_id),
    value_(value) {}

const std::string& PlatformCharacteristicValueChanged::device_id() const {
  return device_id_;
}

void PlatformCharacteristicValueChanged::set_device_id(std::string_view value_arg) {
  device_id_ = value_arg;
}


const std::string& PlatformCharacteristicValueChanged::service_uuid() const {
  return service_uuid_;
}

void PlatformCharacteristicValueChanged::set_service_uuid(std::string_view value_arg) {
  service_uuid_ = value_arg;
}


const std::string& PlatformCharacteristicValueChanged::characteristic_id() const {
  return characteristic_id_;
}

void PlatformCharacteristicValueChanged::set_characteristic_id(std::string_view value_arg) {
  characteristic_id_ = value_arg;
}


const std::vector<uint8_t>& PlatformCharacteristicValueChanged::value() const {
  return value_;
}

void PlatformCharacteristicValueChanged::set_value(const std::vector<uint8_t>& value_arg) {
  value_ = value_arg;
}


EncodableList PlatformCharacteristicValueChanged::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(device_id_));
  list.push_back(EncodableValue(service_uuid_));
  list.push_back(EncodableValue(characteristic_id_));
  list.push_back(EncodableValue(value_));
  return list;
}

PlatformCharacteristicValueChanged PlatformCharacteristicValueChanged::FromEncodableList(const EncodableList& list) {
  PlatformCharacteristicValueChanged decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::vector<uint8_t>>(list[3]));
  return decoded;
}

bool PlatformCharacteristicValueChanged::operator==(const PlatformCharacteristicValueChanged& other) const {
  return PigeonInternalDeepEquals(device_id_, other.device_id_) && PigeonInternalDeepEquals(service_uuid_, other.service_uuid_) && PigeonInternalDeepEquals(characteristic_id_, other.characteristic_id_) && PigeonInternalDeepEquals(value_, other.value_);
}

bool PlatformCharacteristicValueChanged::operator!=(const PlatformCharacteristicValueChanged& other) const {
  return !(*this == other);
}

size_t PlatformCharacteristicValueChanged::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(device_id_);
  result = result * 31 + PigeonInternalDeepHash(service_uuid_);
  result = result * 31 + PigeonInternalDeepHash(characteristic_id_);
  result = result * 31 + PigeonInternalDeepHash(value_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PlatformCharacteristicValueChanged& obj) {
  os << "PlatformCharacteristicValueChanged(";
  os << "device_id: ";
  os << PigeonInternalToString(obj.device_id_);
  os << ", service_uuid: ";
  os << PigeonInternalToString(obj.service_uuid_);
  os << ", characteristic_id: ";
  os << PigeonInternalToString(obj.characteristic_id_);
  os << ", value: ";
  os << PigeonInternalToString(obj.value_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PlatformCharacteristicValueChanged& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformBleInputProperty>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformBleOutputProperty>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformWindowsScanMode>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformConnectionState>(enum_arg_value));
      }
    case 133: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformGattStatus>(enum_arg_value));
      }
    case 134: {
        return CustomEncodableValue(PlatformWindowsSignalStrengthFilter::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(PlatformWindowsScanOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(PlatformScanResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(PlatformConnectionStateChange::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(PlatformServiceDiscovered::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(PlatformCharacteristic::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 140: {
        return CustomEncodableValue(PlatformCharacteristicValueChanged::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PlatformBleInputProperty)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformBleInputProperty>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformBleOutputProperty)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformBleOutputProperty>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformWindowsScanMode)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformWindowsScanMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformConnectionState)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformConnectionState>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformGattStatus)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformGattStatus>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformWindowsSignalStrengthFilter)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<PlatformWindowsSignalStrengthFilter>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformWindowsScanOptions)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<PlatformWindowsScanOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformScanResult)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<PlatformScanResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformConnectionStateChange)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<PlatformConnectionStateChange>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformServiceDiscovered)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<PlatformServiceDiscovered>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformCharacteristic)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<PlatformCharacteristic>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformCharacteristicValueChanged)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(std::any_cast<PlatformCharacteristicValueChanged>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by QuickBlueApi.
const ::flutter::StandardMessageCodec& QuickBlueApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `QuickBlueApi` to handle messages through the `binary_messenger`.
void QuickBlueApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  QuickBlueApi* api) {
  QuickBlueApi::SetUp(binary_messenger, api, "");
}

void QuickBlueApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  QuickBlueApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.isBluetoothAvailable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->IsBluetoothAvailable();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.startScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_service_uuids_arg = args.at(0);
          const auto* service_uuids_arg = std::get_if<EncodableList>(&encodable_service_uuids_arg);
          const auto& encodable_manufacturer_data_arg = args.at(1);
          const auto* manufacturer_data_arg = std::get_if<EncodableMap>(&encodable_manufacturer_data_arg);
          const auto& encodable_rssi_arg = args.at(2);
          const auto* rssi_arg = std::get_if<int64_t>(&encodable_rssi_arg);
          const auto& encodable_options_arg = args.at(3);
          const auto* options_arg = encodable_options_arg.IsNull() ? nullptr : &(std::any_cast<const PlatformWindowsScanOptions&>(std::get<CustomEncodableValue>(encodable_options_arg)));
          std::optional<FlutterError> output = api->StartScan(service_uuids_arg, manufacturer_data_arg, rssi_arg, options_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.stopScan" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StopScan();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.connectedDeviceIds" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_service_uuids_arg = args.at(0);
          if (encodable_service_uuids_arg.IsNull()) {
            reply(WrapError("service_uuids_arg unexpectedly null."));
            return;
          }
          const auto& service_uuids_arg = std::get<EncodableList>(encodable_service_uuids_arg);
          ErrorOr<EncodableList> output = api->ConnectedDeviceIds(service_uuids_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.connect" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          std::optional<FlutterError> output = api->Connect(device_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.disconnect" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          std::optional<FlutterError> output = api->Disconnect(device_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.discoverServices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          api->DiscoverServices(device_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.setNotifiable" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          const auto& encodable_service_arg = args.at(1);
          if (encodable_service_arg.IsNull()) {
            reply(WrapError("service_arg unexpectedly null."));
            return;
          }
          const auto& service_arg = std::get<std::string>(encodable_service_arg);
          const auto& encodable_characteristic_arg = args.at(2);
          if (encodable_characteristic_arg.IsNull()) {
            reply(WrapError("characteristic_arg unexpectedly null."));
            return;
          }
          const auto& characteristic_arg = std::get<std::string>(encodable_characteristic_arg);
          const auto& encodable_ble_input_property_arg = args.at(3);
          if (encodable_ble_input_property_arg.IsNull()) {
            reply(WrapError("ble_input_property_arg unexpectedly null."));
            return;
          }
          const auto& ble_input_property_arg = std::any_cast<const PlatformBleInputProperty&>(std::get<CustomEncodableValue>(encodable_ble_input_property_arg));
          api->SetNotifiable(device_id_arg, service_arg, characteristic_arg, ble_input_property_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.readValue" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          const auto& encodable_service_arg = args.at(1);
          if (encodable_service_arg.IsNull()) {
            reply(WrapError("service_arg unexpectedly null."));
            return;
          }
          const auto& service_arg = std::get<std::string>(encodable_service_arg);
          const auto& encodable_characteristic_arg = args.at(2);
          if (encodable_characteristic_arg.IsNull()) {
            reply(WrapError("characteristic_arg unexpectedly null."));
            return;
          }
          const auto& characteristic_arg = std::get<std::string>(encodable_characteristic_arg);
          api->ReadValue(device_id_arg, service_arg, characteristic_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.writeValue" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          const auto& encodable_service_arg = args.at(1);
          if (encodable_service_arg.IsNull()) {
            reply(WrapError("service_arg unexpectedly null."));
            return;
          }
          const auto& service_arg = std::get<std::string>(encodable_service_arg);
          const auto& encodable_characteristic_arg = args.at(2);
          if (encodable_characteristic_arg.IsNull()) {
            reply(WrapError("characteristic_arg unexpectedly null."));
            return;
          }
          const auto& characteristic_arg = std::get<std::string>(encodable_characteristic_arg);
          const auto& encodable_value_arg = args.at(3);
          if (encodable_value_arg.IsNull()) {
            reply(WrapError("value_arg unexpectedly null."));
            return;
          }
          const auto& value_arg = std::get<std::vector<uint8_t>>(encodable_value_arg);
          const auto& encodable_ble_output_property_arg = args.at(4);
          if (encodable_ble_output_property_arg.IsNull()) {
            reply(WrapError("ble_output_property_arg unexpectedly null."));
            return;
          }
          const auto& ble_output_property_arg = std::any_cast<const PlatformBleOutputProperty&>(std::get<CustomEncodableValue>(encodable_ble_output_property_arg));
          api->WriteValue(device_id_arg, service_arg, characteristic_arg, value_arg, ble_output_property_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.requestMtu" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_id_arg = args.at(0);
          if (encodable_device_id_arg.IsNull()) {
            reply(WrapError("device_id_arg unexpectedly null."));
            return;
          }
          const auto& device_id_arg = std::get<std::string>(encodable_device_id_arg);
          const auto& encodable_expected_mtu_arg = args.at(1);
          if (encodable_expected_mtu_arg.IsNull()) {
            reply(WrapError("expected_mtu_arg unexpectedly null."));
            return;
          }
          const int64_t expected_mtu_arg = encodable_expected_mtu_arg.LongValue();
          api->RequestMtu(device_id_arg, expected_mtu_arg, [reply](ErrorOr<int64_t>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue QuickBlueApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue QuickBlueApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
QuickBlueFlutterApi::QuickBlueFlutterApi(::flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

QuickBlueFlutterApi::QuickBlueFlutterApi(
  ::flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const ::flutter::StandardMessageCodec& QuickBlueFlutterApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void QuickBlueFlutterApi::OnConnectionStateChange(
  const PlatformConnectionStateChange& state_change_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onConnectionStateChange" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(state_change_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void QuickBlueFlutterApi::OnServiceDiscovered(
  const PlatformServiceDiscovered& service_discovered_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onServiceDiscovered" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(service_discovered_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void QuickBlueFlutterApi::OnServiceDiscoveryComplete(
  const std::string& device_id_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onServiceDiscoveryComplete" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(device_id_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void QuickBlueFlutterApi::OnCharacteristicValueChanged(
  const PlatformCharacteristicValueChanged& value_changed_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onCharacteristicValueChanged" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(value_changed_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace quick_blue_windows
