// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings for BlueZ L2CAP support in quick_blue_linux.
class bluez_bindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  bluez_bindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  bluez_bindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int close(int __fd) {
    return _close(__fd);
  }

  late final _closePtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'close',
  );
  late final _close = _closePtr.asFunction<int Function(int)>();

  int connect(int __fd, ffi.Pointer<sockaddr> __addr, int __len) {
    return _connect(__fd, __addr, __len);
  }

  late final _connectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<sockaddr>, ffi.UnsignedInt)
        >
      >('connect');
  late final _connect = _connectPtr
      .asFunction<int Function(int, ffi.Pointer<sockaddr>, int)>();

  int fcntl(int __fd, int __cmd) {
    return _fcntl(__fd, __cmd);
  }

  late final _fcntlPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('fcntl');
  late final _fcntl = _fcntlPtr.asFunction<int Function(int, int)>();

  int getsockopt(
    int __fd,
    int __level,
    int __optname,
    ffi.Pointer<ffi.Void> __optval,
    ffi.Pointer<ffi.UnsignedInt> __optlen,
  ) {
    return _getsockopt(__fd, __level, __optname, __optval, __optlen);
  }

  late final _getsockoptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.UnsignedInt>,
          )
        >
      >('getsockopt');
  late final _getsockopt = _getsockoptPtr
      .asFunction<
        int Function(
          int,
          int,
          int,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.UnsignedInt>,
        )
      >();

  int recv(int __fd, ffi.Pointer<ffi.Void> __buf, int __n, int __flags) {
    return _recv(__fd, __buf, __n, __flags);
  }

  late final _recvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size, ffi.Int)
        >
      >('recv');
  late final _recv = _recvPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int, int)>();

  int send(int __fd, ffi.Pointer<ffi.Void> __buf, int __n, int __flags) {
    return _send(__fd, __buf, __n, __flags);
  }

  late final _sendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Int, ffi.Pointer<ffi.Void>, ffi.Size, ffi.Int)
        >
      >('send');
  late final _send = _sendPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Void>, int, int)>();

  int setsockopt(
    int __fd,
    int __level,
    int __optname,
    ffi.Pointer<ffi.Void> __optval,
    int __optlen,
  ) {
    return _setsockopt(__fd, __level, __optname, __optval, __optlen);
  }

  late final _setsockoptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedInt,
          )
        >
      >('setsockopt');
  late final _setsockopt = _setsockoptPtr
      .asFunction<int Function(int, int, int, ffi.Pointer<ffi.Void>, int)>();

  int socket(int __domain, int __type, int __protocol) {
    return _socket(__domain, __type, __protocol);
  }

  late final _socketPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'socket',
      );
  late final _socket = _socketPtr.asFunction<int Function(int, int, int)>();

  int str2ba(ffi.Pointer<ffi.Char> str, ffi.Pointer<bdaddr_t> ba) {
    return _str2ba(str, ba);
  }

  late final _str2baPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<bdaddr_t>)
        >
      >('str2ba');
  late final _str2ba = _str2baPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<bdaddr_t>)>();
}

const int AF_BLUETOOTH = 31;

const int BDADDR_LE_PUBLIC = 1;

const int BDADDR_LE_RANDOM = 2;

const int BTPROTO_L2CAP = 0;

const int BT_SECURITY = 4;

const int BT_SECURITY_HIGH = 3;

const int BT_SECURITY_LOW = 1;

const int BT_SECURITY_MEDIUM = 2;

const int F_GETFL = 3;

const int F_SETFL = 4;

const int L2CAP_OPTIONS = 1;

const int MSG_DONTWAIT = 64;

const int O_NONBLOCK = 2048;

const int SOCK_SEQPACKET = 5;

const int SOL_BLUETOOTH = 274;

const int SOL_L2CAP = 6;

@ffi.Packed(1)
final class bdaddr_t extends ffi.Struct {
  @ffi.Array.multi([6])
  external ffi.Array<ffi.Uint8> b;
}

final class bt_security extends ffi.Struct {
  @ffi.Uint8()
  external int level;

  @ffi.Uint8()
  external int key_size;

  static ffi.Pointer<bt_security> $allocate(
    ffi.Allocator $allocator, {
    required int level,
    required int key_size,
  }) => $allocator<bt_security>()
    ..ref.level = level
    ..ref.key_size = key_size;
}

final class l2cap_options extends ffi.Struct {
  @ffi.Uint16()
  external int omtu;

  @ffi.Uint16()
  external int imtu;

  @ffi.Uint16()
  external int flush_to;

  @ffi.Uint8()
  external int mode;

  @ffi.Uint8()
  external int fcs;

  @ffi.Uint8()
  external int max_tx;

  @ffi.Uint16()
  external int txwin_size;

  static ffi.Pointer<l2cap_options> $allocate(
    ffi.Allocator $allocator, {
    required int omtu,
    required int imtu,
    required int flush_to,
    required int mode,
    required int fcs,
    required int max_tx,
    required int txwin_size,
  }) => $allocator<l2cap_options>()
    ..ref.omtu = omtu
    ..ref.imtu = imtu
    ..ref.flush_to = flush_to
    ..ref.mode = mode
    ..ref.fcs = fcs
    ..ref.max_tx = max_tx
    ..ref.txwin_size = txwin_size;
}

final class sockaddr extends ffi.Struct {
  @ffi.UnsignedShort()
  external int sa_family;

  @ffi.Array.multi([14])
  external ffi.Array<ffi.Char> sa_data;
}

final class sockaddr_l2 extends ffi.Struct {
  @ffi.UnsignedShort()
  external int l2_family;

  @ffi.UnsignedShort()
  external int l2_psm;

  external bdaddr_t l2_bdaddr;

  @ffi.UnsignedShort()
  external int l2_cid;

  @ffi.Uint8()
  external int l2_bdaddr_type;
}
