name: quick_blue_darwin
description: darwin implementation of the quick_blue plugin.
version: 0.4.0-dev.0

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.2"

resolution: workspace

dependencies:
  quick_blue_platform_interface: ^0.4.0-dev.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^27.1.0

flutter:
  plugin:
    implements: quick_blue
    platforms:
      macos:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
      ios:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
