name: quick_blue_darwin
description: darwin implementation of the quick_blue plugin.
version: 0.5.0
homepage: https://github.com/prefanatic/quick_blue
repository: https://github.com/prefanatic/quick_blue/tree/master/quick_blue_darwin

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.2"

resolution: workspace

dependencies:
  quick_blue_platform_interface: ^0.5.0
  flutter:
    sdk: flutter
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^27.1.0

flutter:
  plugin:
    implements: quick_blue
    platforms:
      macos:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
      ios:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
