name: quick_blue_darwin
description: darwin implementation of the quick_blue plugin.
version: 0.5.0
homepage: https://github.com/prefanatic/quick_blue
repository: https://github.com/prefanatic/quick_blue/tree/master/quick_blue_darwin

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.2"

resolution: workspace

dependencies:
  quick_blue_platform_interface: ^0.5.0
  flutter:
    sdk: flutter
  meta: ^1.18.0
  ffi: ^2.1.5
  objective_c: '>=9.5.0 <9.6.0'
  code_assets: ^1.2.1
  hooks: ^2.2.0
  native_toolchain_c: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^21.0.0

flutter:
  plugin:
    implements: quick_blue
    platforms:
      macos:
        dartPluginClass: QuickBlueDarwin
      ios:
        dartPluginClass: QuickBlueDarwin
