// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlatformBleInputProperty(val raw: Int) {
  DISABLED(0),
  NOTIFICATION(1),
  INDICATION(2);

  companion object {
    fun ofRaw(raw: Int): PlatformBleInputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformBleOutputProperty(val raw: Int) {
  WITH_RESPONSE(0),
  WITHOUT_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): PlatformBleOutputProperty? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformBluetoothState(val raw: Int) {
  UNKNOWN(0),
  UNAVAILABLE(1),
  UNAUTHORIZED(2),
  POWERED_OFF(3),
  POWERED_ON(4);

  companion object {
    fun ofRaw(raw: Int): PlatformBluetoothState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformConnectionState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): PlatformConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformGattStatus(val raw: Int) {
  SUCCESS(0),
  FAILURE(1);

  companion object {
    fun ofRaw(raw: Int): PlatformGattStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCompanionDevice (
  val id: String,
  val name: String,
  val associationId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCompanionDevice {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val associationId = pigeonVar_list[2] as Long
      return PlatformCompanionDevice(id, name, associationId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      associationId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformCompanionDevice
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.associationId, other.associationId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.associationId)
    return result
  }
  override fun toString(): String {
    return "PlatformCompanionDevice(id=$id, name=$name, associationId=$associationId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformScanResult (
  val name: String,
  val deviceId: String,
  val manufacturerDataHead: ByteArray,
  val manufacturerData: ByteArray,
  val rssi: Long,
  val serviceUuids: List<String>,
  val serviceData: Map<String, ByteArray>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformScanResult {
      val name = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val manufacturerDataHead = pigeonVar_list[2] as ByteArray
      val manufacturerData = pigeonVar_list[3] as ByteArray
      val rssi = pigeonVar_list[4] as Long
      val serviceUuids = pigeonVar_list[5] as List<String>
      val serviceData = pigeonVar_list[6] as Map<String, ByteArray>
      return PlatformScanResult(name, deviceId, manufacturerDataHead, manufacturerData, rssi, serviceUuids, serviceData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      deviceId,
      manufacturerDataHead,
      manufacturerData,
      rssi,
      serviceUuids,
      serviceData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformScanResult
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.manufacturerDataHead, other.manufacturerDataHead) && MessagesPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && MessagesPigeonUtils.deepEquals(this.rssi, other.rssi) && MessagesPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && MessagesPigeonUtils.deepEquals(this.serviceData, other.serviceData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerDataHead)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rssi)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceData)
    return result
  }
  override fun toString(): String {
    return "PlatformScanResult(name=$name, deviceId=$deviceId, manufacturerDataHead=${manufacturerDataHead.contentToString()}, manufacturerData=${manufacturerData.contentToString()}, rssi=$rssi, serviceUuids=$serviceUuids, serviceData=$serviceData)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformConnectionStateChange (
  val deviceId: String,
  val state: PlatformConnectionState,
  val gattStatus: PlatformGattStatus
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformConnectionStateChange {
      val deviceId = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as PlatformConnectionState
      val gattStatus = pigeonVar_list[2] as PlatformGattStatus
      return PlatformConnectionStateChange(deviceId, state, gattStatus)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      state,
      gattStatus,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformConnectionStateChange
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.gattStatus, other.gattStatus)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gattStatus)
    return result
  }
  override fun toString(): String {
    return "PlatformConnectionStateChange(deviceId=$deviceId, state=$state, gattStatus=$gattStatus)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformServiceDiscovered (
  val deviceId: String,
  val serviceUuid: String,
  val characteristics: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformServiceDiscovered {
      val deviceId = pigeonVar_list[0] as String
      val serviceUuid = pigeonVar_list[1] as String
      val characteristics = pigeonVar_list[2] as List<String>
      return PlatformServiceDiscovered(deviceId, serviceUuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      serviceUuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformServiceDiscovered
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && MessagesPigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristics)
    return result
  }
  override fun toString(): String {
    return "PlatformServiceDiscovered(deviceId=$deviceId, serviceUuid=$serviceUuid, characteristics=$characteristics)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformMtuChange (
  val deviceId: String,
  val mtu: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformMtuChange {
      val deviceId = pigeonVar_list[0] as String
      val mtu = pigeonVar_list[1] as Long
      return PlatformMtuChange(deviceId, mtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      mtu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformMtuChange
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.mtu, other.mtu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mtu)
    return result
  }
  override fun toString(): String {
    return "PlatformMtuChange(deviceId=$deviceId, mtu=$mtu)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformCharacteristicValueChanged (
  val deviceId: String,
  val characteristicId: String,
  val value: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformCharacteristicValueChanged {
      val deviceId = pigeonVar_list[0] as String
      val characteristicId = pigeonVar_list[1] as String
      val value = pigeonVar_list[2] as ByteArray
      return PlatformCharacteristicValueChanged(deviceId, characteristicId, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      characteristicId,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformCharacteristicValueChanged
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.characteristicId, other.characteristicId) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.characteristicId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "PlatformCharacteristicValueChanged(deviceId=$deviceId, characteristicId=$characteristicId, value=${value.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformL2CapSocketEvent (
  val deviceId: String,
  val data: ByteArray? = null,
  val error: String? = null,
  val opened: Boolean? = null,
  val closed: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformL2CapSocketEvent {
      val deviceId = pigeonVar_list[0] as String
      val data = pigeonVar_list[1] as ByteArray?
      val error = pigeonVar_list[2] as String?
      val opened = pigeonVar_list[3] as Boolean?
      val closed = pigeonVar_list[4] as Boolean?
      return PlatformL2CapSocketEvent(deviceId, data, error, opened, closed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      data,
      error,
      opened,
      closed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformL2CapSocketEvent
    return MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId) && MessagesPigeonUtils.deepEquals(this.data, other.data) && MessagesPigeonUtils.deepEquals(this.error, other.error) && MessagesPigeonUtils.deepEquals(this.opened, other.opened) && MessagesPigeonUtils.deepEquals(this.closed, other.closed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.data)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.opened)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.closed)
    return result
  }
  override fun toString(): String {
    return "PlatformL2CapSocketEvent(deviceId=$deviceId, data=${data?.contentToString()}, error=$error, opened=$opened, closed=$closed)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformBleInputProperty.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformBleOutputProperty.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformBluetoothState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformConnectionState.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformGattStatus.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCompanionDevice.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformScanResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformConnectionStateChange.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformServiceDiscovered.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformMtuChange.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformCharacteristicValueChanged.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformL2CapSocketEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformBleInputProperty -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformBleOutputProperty -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformBluetoothState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformConnectionState -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformGattStatus -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformCompanionDevice -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PlatformScanResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PlatformConnectionStateChange -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PlatformServiceDiscovered -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PlatformMtuChange -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PlatformCharacteristicValueChanged -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PlatformL2CapSocketEvent -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface QuickBlueApi {
  fun isBluetoothAvailable(): Boolean
  fun startScan(serviceUuids: List<String>?, manufacturerData: Map<Long, ByteArray>?)
  fun stopScan()
  fun connect(deviceId: String)
  fun disconnect(deviceId: String)
  fun companionAssociate(deviceId: String?, serviceUuids: List<String>?, manufacturerData: Map<Long, ByteArray>?, callback: (Result<PlatformCompanionDevice?>) -> Unit)
  fun companionDisassociate(associationId: Long)
  fun getCompanionAssociations(): List<PlatformCompanionDevice>
  fun discoverServices(deviceId: String)
  fun setNotifiable(deviceId: String, service: String, characteristic: String, bleInputProperty: PlatformBleInputProperty)
  fun readValue(deviceId: String, service: String, characteristic: String)
  fun writeValue(deviceId: String, service: String, characteristic: String, value: ByteArray, bleOutputProperty: PlatformBleOutputProperty, callback: (Result<Unit>) -> Unit)
  fun requestMtu(deviceId: String, expectedMtu: Long): Long
  fun openL2cap(deviceId: String, psm: Long, callback: (Result<Unit>) -> Unit)
  fun closeL2cap(deviceId: String)
  fun writeL2cap(deviceId: String, value: ByteArray)

  companion object {
    /** The codec used by QuickBlueApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `QuickBlueApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: QuickBlueApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.isBluetoothAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isBluetoothAvailable())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidsArg = args[0] as List<String>?
            val manufacturerDataArg = args[1] as Map<Long, ByteArray>?
            val wrapped: List<Any?> = try {
              api.startScan(serviceUuidsArg, manufacturerDataArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopScan()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.connect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.companionAssociate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String?
            val serviceUuidsArg = args[1] as List<String>?
            val manufacturerDataArg = args[2] as Map<Long, ByteArray>?
            api.companionAssociate(deviceIdArg, serviceUuidsArg, manufacturerDataArg) { result: Result<PlatformCompanionDevice?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.companionDisassociate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val associationIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.companionDisassociate(associationIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.getCompanionAssociations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCompanionAssociations())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.discoverServices(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.setNotifiable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            val bleInputPropertyArg = args[3] as PlatformBleInputProperty
            val wrapped: List<Any?> = try {
              api.setNotifiable(deviceIdArg, serviceArg, characteristicArg, bleInputPropertyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.readValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.readValue(deviceIdArg, serviceArg, characteristicArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.writeValue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val serviceArg = args[1] as String
            val characteristicArg = args[2] as String
            val valueArg = args[3] as ByteArray
            val bleOutputPropertyArg = args[4] as PlatformBleOutputProperty
            api.writeValue(deviceIdArg, serviceArg, characteristicArg, valueArg, bleOutputPropertyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.requestMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val expectedMtuArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.requestMtu(deviceIdArg, expectedMtuArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.openL2cap$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val psmArg = args[1] as Long
            api.openL2cap(deviceIdArg, psmArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.closeL2cap$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.closeL2cap(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.quick_blue.QuickBlueApi.writeL2cap$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val valueArg = args[1] as ByteArray
            val wrapped: List<Any?> = try {
              api.writeL2cap(deviceIdArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}

abstract class BluetoothStateStreamHandler : MessagesPigeonEventChannelWrapper<PlatformBluetoothState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: BluetoothStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.quick_blue.QuickBlueEventApi.bluetoothState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformBluetoothState>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformBluetoothState>) {}

override fun onCancel(p0: Any?) {}
}

abstract class ScanResultsStreamHandler : MessagesPigeonEventChannelWrapper<PlatformScanResult> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ScanResultsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.quick_blue.QuickBlueEventApi.scanResults"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformScanResult>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformScanResult>) {}

override fun onCancel(p0: Any?) {}
}

abstract class MtuChangedStreamHandler : MessagesPigeonEventChannelWrapper<PlatformMtuChange> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: MtuChangedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.quick_blue.QuickBlueEventApi.mtuChanged"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformMtuChange>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformMtuChange>) {}

override fun onCancel(p0: Any?) {}
}

abstract class L2CapSocketEventsStreamHandler : MessagesPigeonEventChannelWrapper<PlatformL2CapSocketEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: L2CapSocketEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.quick_blue.QuickBlueEventApi.l2CapSocketEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformL2CapSocketEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformL2CapSocketEvent>) {}

override fun onCancel(p0: Any?) {}
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class QuickBlueFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by QuickBlueFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onConnectionStateChange(stateChangeArg: PlatformConnectionStateChange, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onConnectionStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateChangeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onServiceDiscovered(serviceDiscoveredArg: PlatformServiceDiscovered, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onServiceDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(serviceDiscoveredArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onServiceDiscoveryComplete(deviceIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onServiceDiscoveryComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onCharacteristicValueChanged(valueChangedArg: PlatformCharacteristicValueChanged, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onCharacteristicValueChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(valueChangedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
