// Copyright (c) 2026, the quick_blue authors.
// Use of this source code is governed by the BSD-3-Clause license.

import 'dart:io';

import 'package:ffigen/ffigen.dart';

final _packageRoot = Platform.script.resolve('../');

void main() {
  _generateCoreBluetooth();
  _generateAccessorySetupKit();
  _generateDispatch();
}

void _generateCoreBluetooth() {
  FfiGenerator(
    headers: Headers(
      entryPoints: [
        Uri.file(
          '$macSdkPath/System/Library/Frameworks/CoreBluetooth.framework/'
          'Headers/CoreBluetooth.h',
        ),
      ],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'CBManager',
        'CBCentralManager',
        'CBPeer',
        'CBPeripheral',
        'CBAttribute',
        'CBService',
        'CBCharacteristic',
        'CBL2CAPChannel',
        'CBUUID',
        'NSUUID',
      }),
      protocols: Protocols.includeSet({
        'CBCentralManagerDelegate',
        'CBPeripheralDelegate',
      }),
    ),
    globals: Globals(
      include: Declarations.includeSet({
        'CBCentralManagerOptionRestoreIdentifierKey',
        'CBCentralManagerScanOptionAllowDuplicatesKey',
        'CBCentralManagerScanOptionSolicitedServiceUUIDsKey',
        'CBCentralManagerRestoredStatePeripheralsKey',
        'CBCentralManagerRestoredStateScanServicesKey',
        'CBCentralManagerRestoredStateScanOptionsKey',
        'CBAdvertisementDataLocalNameKey',
        'CBAdvertisementDataServiceUUIDsKey',
        'CBAdvertisementDataServiceDataKey',
        'CBAdvertisementDataManufacturerDataKey',
        'NSDefaultRunLoopMode',
      }),
    ),
    output: Output(
      dartFile: _packageRoot.resolve(
        'lib/src/third_party/core_bluetooth.g.dart',
      ),
      objectiveCFile: _packageRoot.resolve('src/generated/core_bluetooth.g.m'),
      style: const NativeExternalBindings(
        assetId: 'package:quick_blue_darwin/quick_blue_darwin_bindings.dylib',
      ),
      preamble: '''
// Generated by package:ffigen. Do not edit.
// CoreBluetooth SDK headers: Copyright 2011 Apple, Inc. All rights reserved.
// Quick Blue binding configuration is covered by the BSD-3-Clause license.
''',
    ),
  ).generate();
  _addNativeCopyright('src/generated/core_bluetooth.g.m');
}

void _generateDispatch() {
  FfiGenerator(
    headers: Headers(
      entryPoints: [_packageRoot.resolve('src/quick_blue_dispatch.h')],
    ),
    functions: Functions.includeSet({'quick_blue_main_queue'}),
    output: Output(
      dartFile: _packageRoot.resolve(
        'lib/src/third_party/quick_blue_dispatch.g.dart',
      ),
      style: const NativeExternalBindings(
        assetId: 'package:quick_blue_darwin/quick_blue_darwin_bindings.dylib',
      ),
      preamble: '''
// Copyright (c) 2026, the quick_blue authors.
// Use of this source code is governed by the BSD-3-Clause license.
// Generated by package:ffigen. Do not edit.
''',
    ),
  ).generate();
}

void _addNativeCopyright(String path) {
  final file = File.fromUri(_packageRoot.resolve(path));
  final source = file.readAsStringSync();
  file.writeAsStringSync('''// Copyright (c) 2026, the quick_blue authors.
// Use of this source code is governed by the BSD-3-Clause license.
// Generated by package:ffigen. Do not edit.

$source''');
}

void _generateAccessorySetupKit() {
  FfiGenerator(
    headers: Headers(
      entryPoints: [_packageRoot.resolve('tool/accessory_setup_kit.h')],
      compilerOptions: [
        '-isysroot',
        iosSdkPath,
        '-F$iosSdkPath/System/Library/Frameworks',
        '-target',
        'arm64-apple-ios13.0',
      ],
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({
        'ASAccessory',
        'ASAccessoryEvent',
        'ASAccessorySession',
        'ASDiscoveryDescriptor',
        'ASPickerDisplayItem',
        'ASMigrationDisplayItem',
        'CBUUID',
        'NSUUID',
        'UIImage',
      }),
    ),
    output: Output(
      dartFile: _packageRoot.resolve(
        'lib/src/third_party/accessory_setup_kit.g.dart',
      ),
      objectiveCFile: _packageRoot.resolve(
        'src/generated/accessory_setup_kit.g.m',
      ),
      style: const NativeExternalBindings(
        assetId: 'package:quick_blue_darwin/quick_blue_darwin_bindings.dylib',
      ),
      preamble: '''
// Generated by package:ffigen. Do not edit.
// AccessorySetupKit SDK headers: Copyright (C) 2024 Apple Inc. All Rights Reserved.
// Quick Blue binding configuration is covered by the BSD-3-Clause license.
''',
    ),
  ).generate();
  _addNativeCopyright('src/generated/accessory_setup_kit.g.m');
}
