// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum PlatformBleInputProperty {
  disabled,
  notification,
  indication,
}

enum PlatformBleOutputProperty {
  withResponse,
  withoutResponse,
}

enum PlatformConnectionState {
  disconnected,
  connecting,
  connected,
  disconnecting,
  unknown,
}

enum PlatformGattStatus {
  success,
  failure,
}

class PlatformScanResult {
  PlatformScanResult({
    required this.name,
    required this.deviceId,
    required this.manufacturerDataHead,
    required this.manufacturerData,
    required this.rssi,
    required this.serviceUuids,
    required this.serviceData,
  });

  String name;

  String deviceId;

  Uint8List manufacturerDataHead;

  Uint8List manufacturerData;

  int rssi;

  List<String> serviceUuids;

  Map<String, Uint8List> serviceData;

  List<Object?> _toList() {
    return <Object?>[
      name,
      deviceId,
      manufacturerDataHead,
      manufacturerData,
      rssi,
      serviceUuids,
      serviceData,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformScanResult decode(Object result) {
    result as List<Object?>;
    return PlatformScanResult(
      name: result[0]! as String,
      deviceId: result[1]! as String,
      manufacturerDataHead: result[2]! as Uint8List,
      manufacturerData: result[3]! as Uint8List,
      rssi: result[4]! as int,
      serviceUuids: (result[5]! as List<Object?>).cast<String>(),
      serviceData: (result[6]! as Map<Object?, Object?>).cast<String, Uint8List>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(deviceId, other.deviceId) && _deepEquals(manufacturerDataHead, other.manufacturerDataHead) && _deepEquals(manufacturerData, other.manufacturerData) && _deepEquals(rssi, other.rssi) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(serviceData, other.serviceData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformScanResult(name: $name, deviceId: $deviceId, manufacturerDataHead: $manufacturerDataHead, manufacturerData: $manufacturerData, rssi: $rssi, serviceUuids: $serviceUuids, serviceData: $serviceData)';
  }
}

class PlatformConnectionStateChange {
  PlatformConnectionStateChange({
    required this.deviceId,
    required this.state,
    required this.gattStatus,
  });

  String deviceId;

  PlatformConnectionState state;

  PlatformGattStatus gattStatus;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      state,
      gattStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformConnectionStateChange decode(Object result) {
    result as List<Object?>;
    return PlatformConnectionStateChange(
      deviceId: result[0]! as String,
      state: result[1]! as PlatformConnectionState,
      gattStatus: result[2]! as PlatformGattStatus,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformConnectionStateChange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(state, other.state) && _deepEquals(gattStatus, other.gattStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformConnectionStateChange(deviceId: $deviceId, state: $state, gattStatus: $gattStatus)';
  }
}

class PlatformServiceDiscovered {
  PlatformServiceDiscovered({
    required this.deviceId,
    required this.serviceUuid,
    required this.characteristics,
  });

  String deviceId;

  String serviceUuid;

  List<PlatformCharacteristic> characteristics;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      serviceUuid,
      characteristics,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformServiceDiscovered decode(Object result) {
    result as List<Object?>;
    return PlatformServiceDiscovered(
      deviceId: result[0]! as String,
      serviceUuid: result[1]! as String,
      characteristics: (result[2]! as List<Object?>).cast<PlatformCharacteristic>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformServiceDiscovered || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristics, other.characteristics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformServiceDiscovered(deviceId: $deviceId, serviceUuid: $serviceUuid, characteristics: $characteristics)';
  }
}

class PlatformCharacteristic {
  PlatformCharacteristic({
    required this.uuid,
    required this.canRead,
    required this.canWriteWithResponse,
    required this.canWriteWithoutResponse,
    required this.canNotify,
    required this.canIndicate,
  });

  String uuid;

  bool canRead;

  bool canWriteWithResponse;

  bool canWriteWithoutResponse;

  bool canNotify;

  bool canIndicate;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      canRead,
      canWriteWithResponse,
      canWriteWithoutResponse,
      canNotify,
      canIndicate,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCharacteristic decode(Object result) {
    result as List<Object?>;
    return PlatformCharacteristic(
      uuid: result[0]! as String,
      canRead: result[1]! as bool,
      canWriteWithResponse: result[2]! as bool,
      canWriteWithoutResponse: result[3]! as bool,
      canNotify: result[4]! as bool,
      canIndicate: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(canRead, other.canRead) && _deepEquals(canWriteWithResponse, other.canWriteWithResponse) && _deepEquals(canWriteWithoutResponse, other.canWriteWithoutResponse) && _deepEquals(canNotify, other.canNotify) && _deepEquals(canIndicate, other.canIndicate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCharacteristic(uuid: $uuid, canRead: $canRead, canWriteWithResponse: $canWriteWithResponse, canWriteWithoutResponse: $canWriteWithoutResponse, canNotify: $canNotify, canIndicate: $canIndicate)';
  }
}

class PlatformCharacteristicValueChanged {
  PlatformCharacteristicValueChanged({
    required this.deviceId,
    required this.serviceUuid,
    required this.characteristicId,
    required this.value,
  });

  String deviceId;

  String serviceUuid;

  String characteristicId;

  Uint8List value;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      serviceUuid,
      characteristicId,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCharacteristicValueChanged decode(Object result) {
    result as List<Object?>;
    return PlatformCharacteristicValueChanged(
      deviceId: result[0]! as String,
      serviceUuid: result[1]! as String,
      characteristicId: result[2]! as String,
      value: result[3]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCharacteristicValueChanged || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristicId, other.characteristicId) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCharacteristicValueChanged(deviceId: $deviceId, serviceUuid: $serviceUuid, characteristicId: $characteristicId, value: $value)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformBleInputProperty) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBleOutputProperty) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformConnectionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PlatformGattStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PlatformScanResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformConnectionStateChange) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformServiceDiscovered) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCharacteristic) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCharacteristicValueChanged) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleInputProperty.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleOutputProperty.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformConnectionState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformGattStatus.values[value];
      case 133:
        return PlatformScanResult.decode(readValue(buffer)!);
      case 134:
        return PlatformConnectionStateChange.decode(readValue(buffer)!);
      case 135:
        return PlatformServiceDiscovered.decode(readValue(buffer)!);
      case 136:
        return PlatformCharacteristic.decode(readValue(buffer)!);
      case 137:
        return PlatformCharacteristicValueChanged.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class QuickBlueApi {
  /// Constructor for [QuickBlueApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  QuickBlueApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isBluetoothAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.isBluetoothAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startScan({List<String>? serviceUuids, Map<int, Uint8List>? manufacturerData}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuids, manufacturerData]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<String>> connectedDeviceIds(List<String> serviceUuids) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.connectedDeviceIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<void> connect(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> discoverServices(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setNotifiable(String deviceId, String service, String characteristic, PlatformBleInputProperty bleInputProperty) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.setNotifiable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic, bleInputProperty]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> readValue(String deviceId, String service, String characteristic) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.readValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> writeValue(String deviceId, String service, String characteristic, Uint8List value, PlatformBleOutputProperty bleOutputProperty) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.writeValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic, value, bleOutputProperty]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> requestMtu(String deviceId, int expectedMtu) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue_windows.QuickBlueApi.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, expectedMtu]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }
}

abstract class QuickBlueFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onConnectionStateChange(PlatformConnectionStateChange stateChange);

  void onServiceDiscovered(PlatformServiceDiscovered serviceDiscovered);

  void onServiceDiscoveryComplete(String deviceId);

  void onCharacteristicValueChanged(PlatformCharacteristicValueChanged valueChanged);

  static void setUp(QuickBlueFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onConnectionStateChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformConnectionStateChange arg_stateChange = args[0]! as PlatformConnectionStateChange;
          try {
            api.onConnectionStateChange(arg_stateChange);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onServiceDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformServiceDiscovered arg_serviceDiscovered = args[0]! as PlatformServiceDiscovered;
          try {
            api.onServiceDiscovered(arg_serviceDiscovered);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onServiceDiscoveryComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          try {
            api.onServiceDiscoveryComplete(arg_deviceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue_windows.QuickBlueFlutterApi.onCharacteristicValueChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformCharacteristicValueChanged arg_valueChanged = args[0]! as PlatformCharacteristicValueChanged;
          try {
            api.onCharacteristicValueChanged(arg_valueChanged);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
