// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum PlatformBleInputProperty {
  disabled,
  notification,
  indication,
}

enum PlatformBleOutputProperty {
  withResponse,
  withoutResponse,
}

enum PlatformBluetoothState {
  unknown,
  unavailable,
  unauthorized,
  poweredOff,
  poweredOn,
}

enum PlatformBondState {
  unknown,
  notBonded,
  bonding,
  bonded,
}

enum PlatformAndroidScanMode {
  opportunistic,
  lowPower,
  balanced,
  lowLatency,
}

enum PlatformAndroidScanCallbackType {
  allMatches,
  firstMatch,
  matchLost,
  firstMatchAndMatchLost,
}

enum PlatformAndroidScanMatchMode {
  aggressive,
  sticky,
}

enum PlatformAndroidScanNumOfMatches {
  one,
  few,
  max,
}

enum PlatformAndroidScanPhy {
  le1m,
  leCoded,
  allSupported,
}

enum PlatformConnectionState {
  disconnected,
  connecting,
  connected,
  disconnecting,
  unknown,
}

enum PlatformGattStatus {
  success,
  failure,
}

class PlatformAndroidScanOptions {
  PlatformAndroidScanOptions({
    required this.scanMode,
    required this.callbackType,
    required this.matchMode,
    this.numOfMatches,
    required this.reportDelayMillis,
    this.legacy,
    this.phy,
  });

  PlatformAndroidScanMode scanMode;

  PlatformAndroidScanCallbackType callbackType;

  PlatformAndroidScanMatchMode matchMode;

  PlatformAndroidScanNumOfMatches? numOfMatches;

  int reportDelayMillis;

  bool? legacy;

  PlatformAndroidScanPhy? phy;

  List<Object?> _toList() {
    return <Object?>[
      scanMode,
      callbackType,
      matchMode,
      numOfMatches,
      reportDelayMillis,
      legacy,
      phy,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformAndroidScanOptions decode(Object result) {
    result as List<Object?>;
    return PlatformAndroidScanOptions(
      scanMode: result[0]! as PlatformAndroidScanMode,
      callbackType: result[1]! as PlatformAndroidScanCallbackType,
      matchMode: result[2]! as PlatformAndroidScanMatchMode,
      numOfMatches: result[3] as PlatformAndroidScanNumOfMatches?,
      reportDelayMillis: result[4]! as int,
      legacy: result[5] as bool?,
      phy: result[6] as PlatformAndroidScanPhy?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAndroidScanOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scanMode, other.scanMode) && _deepEquals(callbackType, other.callbackType) && _deepEquals(matchMode, other.matchMode) && _deepEquals(numOfMatches, other.numOfMatches) && _deepEquals(reportDelayMillis, other.reportDelayMillis) && _deepEquals(legacy, other.legacy) && _deepEquals(phy, other.phy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformAndroidScanOptions(scanMode: $scanMode, callbackType: $callbackType, matchMode: $matchMode, numOfMatches: $numOfMatches, reportDelayMillis: $reportDelayMillis, legacy: $legacy, phy: $phy)';
  }
}

class PlatformBleCompanionFilter {
  PlatformBleCompanionFilter({
    this.deviceId,
    this.namePattern,
    required this.serviceUuids,
    this.manufacturerData,
  });

  String? deviceId;

  String? namePattern;

  List<String> serviceUuids;

  Map<int, Uint8List>? manufacturerData;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      namePattern,
      serviceUuids,
      manufacturerData,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformBleCompanionFilter decode(Object result) {
    result as List<Object?>;
    return PlatformBleCompanionFilter(
      deviceId: result[0] as String?,
      namePattern: result[1] as String?,
      serviceUuids: (result[2]! as List<Object?>).cast<String>(),
      manufacturerData: (result[3] as Map<Object?, Object?>?)?.cast<int, Uint8List>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformBleCompanionFilter || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(namePattern, other.namePattern) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(manufacturerData, other.manufacturerData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformBleCompanionFilter(deviceId: $deviceId, namePattern: $namePattern, serviceUuids: $serviceUuids, manufacturerData: $manufacturerData)';
  }
}

class PlatformCompanionAssociationRequest {
  PlatformCompanionAssociationRequest({
    required this.filters,
    required this.singleDevice,
  });

  List<PlatformBleCompanionFilter> filters;

  bool singleDevice;

  List<Object?> _toList() {
    return <Object?>[
      filters,
      singleDevice,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCompanionAssociationRequest decode(Object result) {
    result as List<Object?>;
    return PlatformCompanionAssociationRequest(
      filters: (result[0]! as List<Object?>).cast<PlatformBleCompanionFilter>(),
      singleDevice: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCompanionAssociationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(filters, other.filters) && _deepEquals(singleDevice, other.singleDevice);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCompanionAssociationRequest(filters: $filters, singleDevice: $singleDevice)';
  }
}

class PlatformCompanionAssociation {
  PlatformCompanionAssociation({
    required this.id,
    this.deviceId,
    this.displayName,
    this.deviceProfile,
  });

  int id;

  String? deviceId;

  String? displayName;

  String? deviceProfile;

  List<Object?> _toList() {
    return <Object?>[
      id,
      deviceId,
      displayName,
      deviceProfile,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCompanionAssociation decode(Object result) {
    result as List<Object?>;
    return PlatformCompanionAssociation(
      id: result[0]! as int,
      deviceId: result[1] as String?,
      displayName: result[2] as String?,
      deviceProfile: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCompanionAssociation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(deviceId, other.deviceId) && _deepEquals(displayName, other.displayName) && _deepEquals(deviceProfile, other.deviceProfile);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCompanionAssociation(id: $id, deviceId: $deviceId, displayName: $displayName, deviceProfile: $deviceProfile)';
  }
}

class PlatformScanResult {
  PlatformScanResult({
    required this.name,
    required this.deviceId,
    required this.manufacturerDataHead,
    required this.manufacturerData,
    required this.rssi,
    required this.serviceUuids,
    required this.serviceData,
  });

  String name;

  String deviceId;

  Uint8List manufacturerDataHead;

  Uint8List manufacturerData;

  int rssi;

  List<String> serviceUuids;

  Map<String, Uint8List> serviceData;

  List<Object?> _toList() {
    return <Object?>[
      name,
      deviceId,
      manufacturerDataHead,
      manufacturerData,
      rssi,
      serviceUuids,
      serviceData,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformScanResult decode(Object result) {
    result as List<Object?>;
    return PlatformScanResult(
      name: result[0]! as String,
      deviceId: result[1]! as String,
      manufacturerDataHead: result[2]! as Uint8List,
      manufacturerData: result[3]! as Uint8List,
      rssi: result[4]! as int,
      serviceUuids: (result[5]! as List<Object?>).cast<String>(),
      serviceData: (result[6]! as Map<Object?, Object?>).cast<String, Uint8List>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(deviceId, other.deviceId) && _deepEquals(manufacturerDataHead, other.manufacturerDataHead) && _deepEquals(manufacturerData, other.manufacturerData) && _deepEquals(rssi, other.rssi) && _deepEquals(serviceUuids, other.serviceUuids) && _deepEquals(serviceData, other.serviceData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformScanResult(name: $name, deviceId: $deviceId, manufacturerDataHead: $manufacturerDataHead, manufacturerData: $manufacturerData, rssi: $rssi, serviceUuids: $serviceUuids, serviceData: $serviceData)';
  }
}

class PlatformConnectionStateChange {
  PlatformConnectionStateChange({
    required this.deviceId,
    required this.state,
    required this.gattStatus,
    this.nativeStatus,
  });

  String deviceId;

  PlatformConnectionState state;

  PlatformGattStatus gattStatus;

  int? nativeStatus;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      state,
      gattStatus,
      nativeStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformConnectionStateChange decode(Object result) {
    result as List<Object?>;
    return PlatformConnectionStateChange(
      deviceId: result[0]! as String,
      state: result[1]! as PlatformConnectionState,
      gattStatus: result[2]! as PlatformGattStatus,
      nativeStatus: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformConnectionStateChange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(state, other.state) && _deepEquals(gattStatus, other.gattStatus) && _deepEquals(nativeStatus, other.nativeStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformConnectionStateChange(deviceId: $deviceId, state: $state, gattStatus: $gattStatus, nativeStatus: $nativeStatus)';
  }
}

class PlatformBondStateChange {
  PlatformBondStateChange({
    required this.deviceId,
    required this.state,
    required this.previousState,
  });

  String deviceId;

  PlatformBondState state;

  PlatformBondState previousState;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      state,
      previousState,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformBondStateChange decode(Object result) {
    result as List<Object?>;
    return PlatformBondStateChange(
      deviceId: result[0]! as String,
      state: result[1]! as PlatformBondState,
      previousState: result[2]! as PlatformBondState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformBondStateChange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(state, other.state) && _deepEquals(previousState, other.previousState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformBondStateChange(deviceId: $deviceId, state: $state, previousState: $previousState)';
  }
}

class PlatformServiceDiscovered {
  PlatformServiceDiscovered({
    required this.deviceId,
    required this.serviceUuid,
    required this.characteristics,
  });

  String deviceId;

  String serviceUuid;

  List<PlatformCharacteristic> characteristics;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      serviceUuid,
      characteristics,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformServiceDiscovered decode(Object result) {
    result as List<Object?>;
    return PlatformServiceDiscovered(
      deviceId: result[0]! as String,
      serviceUuid: result[1]! as String,
      characteristics: (result[2]! as List<Object?>).cast<PlatformCharacteristic>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformServiceDiscovered || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristics, other.characteristics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformServiceDiscovered(deviceId: $deviceId, serviceUuid: $serviceUuid, characteristics: $characteristics)';
  }
}

class PlatformCharacteristic {
  PlatformCharacteristic({
    required this.uuid,
    required this.canRead,
    required this.canWriteWithResponse,
    required this.canWriteWithoutResponse,
    required this.canNotify,
    required this.canIndicate,
  });

  String uuid;

  bool canRead;

  bool canWriteWithResponse;

  bool canWriteWithoutResponse;

  bool canNotify;

  bool canIndicate;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      canRead,
      canWriteWithResponse,
      canWriteWithoutResponse,
      canNotify,
      canIndicate,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCharacteristic decode(Object result) {
    result as List<Object?>;
    return PlatformCharacteristic(
      uuid: result[0]! as String,
      canRead: result[1]! as bool,
      canWriteWithResponse: result[2]! as bool,
      canWriteWithoutResponse: result[3]! as bool,
      canNotify: result[4]! as bool,
      canIndicate: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uuid, other.uuid) && _deepEquals(canRead, other.canRead) && _deepEquals(canWriteWithResponse, other.canWriteWithResponse) && _deepEquals(canWriteWithoutResponse, other.canWriteWithoutResponse) && _deepEquals(canNotify, other.canNotify) && _deepEquals(canIndicate, other.canIndicate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCharacteristic(uuid: $uuid, canRead: $canRead, canWriteWithResponse: $canWriteWithResponse, canWriteWithoutResponse: $canWriteWithoutResponse, canNotify: $canNotify, canIndicate: $canIndicate)';
  }
}

class PlatformMtuChange {
  PlatformMtuChange({
    required this.deviceId,
    required this.mtu,
  });

  String deviceId;

  int mtu;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      mtu,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformMtuChange decode(Object result) {
    result as List<Object?>;
    return PlatformMtuChange(
      deviceId: result[0]! as String,
      mtu: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMtuChange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(mtu, other.mtu);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformMtuChange(deviceId: $deviceId, mtu: $mtu)';
  }
}

class PlatformCharacteristicValueChanged {
  PlatformCharacteristicValueChanged({
    required this.deviceId,
    required this.serviceUuid,
    required this.characteristicId,
    required this.value,
  });

  String deviceId;

  String serviceUuid;

  String characteristicId;

  Uint8List value;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      serviceUuid,
      characteristicId,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformCharacteristicValueChanged decode(Object result) {
    result as List<Object?>;
    return PlatformCharacteristicValueChanged(
      deviceId: result[0]! as String,
      serviceUuid: result[1]! as String,
      characteristicId: result[2]! as String,
      value: result[3]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCharacteristicValueChanged || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristicId, other.characteristicId) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformCharacteristicValueChanged(deviceId: $deviceId, serviceUuid: $serviceUuid, characteristicId: $characteristicId, value: $value)';
  }
}

class PlatformL2CapSocketEvent {
  PlatformL2CapSocketEvent({
    required this.deviceId,
    this.data,
    this.error,
    this.opened,
    this.closed,
  });

  String deviceId;

  Uint8List? data;

  String? error;

  bool? opened;

  bool? closed;

  List<Object?> _toList() {
    return <Object?>[
      deviceId,
      data,
      error,
      opened,
      closed,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformL2CapSocketEvent decode(Object result) {
    result as List<Object?>;
    return PlatformL2CapSocketEvent(
      deviceId: result[0]! as String,
      data: result[1] as Uint8List?,
      error: result[2] as String?,
      opened: result[3] as bool?,
      closed: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformL2CapSocketEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceId, other.deviceId) && _deepEquals(data, other.data) && _deepEquals(error, other.error) && _deepEquals(opened, other.opened) && _deepEquals(closed, other.closed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformL2CapSocketEvent(deviceId: $deviceId, data: $data, error: $error, opened: $opened, closed: $closed)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformBleInputProperty) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBleOutputProperty) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBluetoothState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBondState) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanMode) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanCallbackType) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanMatchMode) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanNumOfMatches) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanPhy) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is PlatformConnectionState) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is PlatformGattStatus) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is PlatformAndroidScanOptions) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformBleCompanionFilter) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCompanionAssociationRequest) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCompanionAssociation) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformScanResult) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformConnectionStateChange) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformBondStateChange) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformServiceDiscovered) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCharacteristic) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformMtuChange) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCharacteristicValueChanged) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformL2CapSocketEvent) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleInputProperty.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleOutputProperty.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBluetoothState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformBondState.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAndroidScanMode.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAndroidScanCallbackType.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAndroidScanMatchMode.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAndroidScanNumOfMatches.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAndroidScanPhy.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformConnectionState.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformGattStatus.values[value];
      case 140:
        return PlatformAndroidScanOptions.decode(readValue(buffer)!);
      case 141:
        return PlatformBleCompanionFilter.decode(readValue(buffer)!);
      case 142:
        return PlatformCompanionAssociationRequest.decode(readValue(buffer)!);
      case 143:
        return PlatformCompanionAssociation.decode(readValue(buffer)!);
      case 144:
        return PlatformScanResult.decode(readValue(buffer)!);
      case 145:
        return PlatformConnectionStateChange.decode(readValue(buffer)!);
      case 146:
        return PlatformBondStateChange.decode(readValue(buffer)!);
      case 147:
        return PlatformServiceDiscovered.decode(readValue(buffer)!);
      case 148:
        return PlatformCharacteristic.decode(readValue(buffer)!);
      case 149:
        return PlatformMtuChange.decode(readValue(buffer)!);
      case 150:
        return PlatformCharacteristicValueChanged.decode(readValue(buffer)!);
      case 151:
        return PlatformL2CapSocketEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class QuickBlueApi {
  /// Constructor for [QuickBlueApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  QuickBlueApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isBluetoothAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.isBluetoothAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startScan({List<String>? serviceUuids, Map<String, Uint8List>? serviceData, Map<int, Uint8List>? manufacturerData, int? rssi, PlatformAndroidScanOptions? options, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuids, serviceData, manufacturerData, rssi, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.stopScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<String>> connectedDeviceIds(List<String> serviceUuids) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.connectedDeviceIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<void> connect(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<PlatformBondState> bondState(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.bondState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformBondState;
  }

  Future<void> pair(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.pair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isCompanionAssociationSupported() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.isCompanionAssociationSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<PlatformCompanionAssociation?> companionAssociate(PlatformCompanionAssociationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.companionAssociate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PlatformCompanionAssociation?;
  }

  Future<void> companionDisassociate(int associationId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.companionDisassociate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[associationId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<PlatformCompanionAssociation>> getCompanionAssociations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.getCompanionAssociations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PlatformCompanionAssociation>();
  }

  Future<void> discoverServices(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.discoverServices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setNotifiable(String deviceId, String service, String characteristic, PlatformBleInputProperty bleInputProperty) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.setNotifiable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic, bleInputProperty]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<Uint8List> readValue(String deviceId, String service, String characteristic) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.readValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  Future<void> writeValue(String deviceId, String service, String characteristic, Uint8List value, PlatformBleOutputProperty bleOutputProperty) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.writeValue$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, service, characteristic, value, bleOutputProperty]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> requestMtu(String deviceId, int expectedMtu) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.requestMtu$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, expectedMtu]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<void> openL2cap(String deviceId, int psm) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.openL2cap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, psm]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> closeL2cap(String deviceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.closeL2cap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> writeL2cap(String deviceId, Uint8List value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.quick_blue.QuickBlueApi.writeL2cap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Returns a broadcast [Stream] of events from the `bluetoothState` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformBluetoothState> bluetoothState( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel bluetoothStateChannel =
      EventChannel('dev.flutter.pigeon.quick_blue.QuickBlueEventApi.bluetoothState$instanceName', pigeonMethodCodec);
  return bluetoothStateChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformBluetoothState;
  });
}
    
/// Returns a broadcast [Stream] of events from the `bondStateChanges` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformBondStateChange> bondStateChanges( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel bondStateChangesChannel =
      EventChannel('dev.flutter.pigeon.quick_blue.QuickBlueEventApi.bondStateChanges$instanceName', pigeonMethodCodec);
  return bondStateChangesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformBondStateChange;
  });
}
    
/// Returns a broadcast [Stream] of events from the `scanResults` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformScanResult> scanResults( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel scanResultsChannel =
      EventChannel('dev.flutter.pigeon.quick_blue.QuickBlueEventApi.scanResults$instanceName', pigeonMethodCodec);
  return scanResultsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformScanResult;
  });
}
    
/// Returns a broadcast [Stream] of events from the `mtuChanged` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformMtuChange> mtuChanged( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel mtuChangedChannel =
      EventChannel('dev.flutter.pigeon.quick_blue.QuickBlueEventApi.mtuChanged$instanceName', pigeonMethodCodec);
  return mtuChangedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformMtuChange;
  });
}
    
/// Returns a broadcast [Stream] of events from the `l2CapSocketEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformL2CapSocketEvent> l2CapSocketEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel l2CapSocketEventsChannel =
      EventChannel('dev.flutter.pigeon.quick_blue.QuickBlueEventApi.l2CapSocketEvents$instanceName', pigeonMethodCodec);
  return l2CapSocketEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformL2CapSocketEvent;
  });
}
    

abstract class QuickBlueFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onConnectionStateChange(PlatformConnectionStateChange stateChange);

  void onServiceDiscovered(PlatformServiceDiscovered serviceDiscovered);

  void onServiceDiscoveryComplete(String deviceId);

  void onCharacteristicValueChanged(PlatformCharacteristicValueChanged valueChanged);

  static void setUp(QuickBlueFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onConnectionStateChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformConnectionStateChange arg_stateChange = args[0]! as PlatformConnectionStateChange;
          try {
            api.onConnectionStateChange(arg_stateChange);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onServiceDiscovered$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformServiceDiscovered arg_serviceDiscovered = args[0]! as PlatformServiceDiscovered;
          try {
            api.onServiceDiscovered(arg_serviceDiscovered);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onServiceDiscoveryComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_deviceId = args[0]! as String;
          try {
            api.onServiceDiscoveryComplete(arg_deviceId);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.quick_blue.QuickBlueFlutterApi.onCharacteristicValueChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PlatformCharacteristicValueChanged arg_valueChanged = args[0]! as PlatformCharacteristicValueChanged;
          try {
            api.onCharacteristicValueChanged(arg_valueChanged);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
